name: 'Build Provenance'
description: 'Generate and display build provenance'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run index.js
      run: node dist/index.js
      shell: bash
    - name: Display provenance.json
      run: cat provenance.json
      shell: bash