name: 'SLSA Provenance Generator'
description: 'Generates SLSA provenance attestation in in-toto format'
inputs:
  github-token:
    description: 'GitHub token for accessing repository information'
    required: true
  output-path:
    description: 'Path where the provenance file will be written'
    required: true
  # target-path:
  #   description: 'Target path for uploading the provenance file'
  #   required: true

runs:
  using: 'node20'
  main: 'dist/index.js'