name: 'Build Provenance'
description: 'Generate and display build provenance'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run compiled index.js
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || secrets.GITHUB_TOKEN }}
    - name: Display provenance.json
      run: cat provenance.json
      shell: bash