name: 'Build Provenance'
description: 'Generate and display build provenance'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  output-path:
    description: 'Path to output the provenance file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run index.js
      run: node dist/index.js
      shell: bash
    - name: Display provenance.json
      run: cat ${{ inputs.output-path }}
      shell: bash