# action.yml
name: 'Evidence Generator for SLSA Build Provenance '
description: 'Evidence Generator for SLSA Build Provenance v1.0 compliant'
inputs:
  artifact-path:
    description: 'Path to the built artifact'
    required: true
  output-path:
    description: 'Path to store the provenance file'
    required: false
    default: 'provenance.json'
  build-url:
    description: 'URL of the build job'
    required: false
    default: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  builder-image:
    description: 'Docker image used for building'
    required: false
    default: 'github-hosted'
  install-jq:
    description: 'Install jq if not present'
    required: false
    default: 'true'

outputs:
  provenance-path:
    description: 'Path to the generated provenance file'
    value: '${{ steps.generate-provenance.outputs.provenance-path }}'

runs:
  using: 'composite'
  steps:
    - name: Install JQ
      if: ${{ inputs.install-jq == 'true' }}
      shell: bash
      run: |
        # Ubuntu-specific jq installation
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Generate SLSA Provenance
      id: generate-provenance
      shell: bash
      env:
        ARTIFACT_PATH: ${{ inputs.artifact-path }}
        OUTPUT_PATH: ${{ inputs.output-path }}
        BUILD_URL: ${{ inputs.build-url }}
        BUILDER_IMAGE: ${{ inputs.builder-image }}
      run: |
        # Verify jq is installed
        if ! command -v jq &> /dev/null; then
          echo "Error: jq is not installed. Set install-jq to 'true' or pre-install jq."
          exit 1
        fi

        # Calculate artifact digest
        artifact_sha256=$(sha256sum "$ARTIFACT_PATH" | cut -d' ' -f1)

        # Current timestamp in RFC 3339 format
        build_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # Generate full SLSA v1.0 compliant provenance
        jq -n \
          --arg buildTimestamp "$build_timestamp" \
          --arg buildUrl "$BUILD_URL" \
          --arg repo "$GITHUB_REPOSITORY" \
          --arg sha "$GITHUB_SHA" \
          --arg runId "$GITHUB_RUN_ID" \
          --arg artifactSha "$artifact_sha256" \
          --arg builderImage "$BUILDER_IMAGE" \
          --arg ref "$GITHUB_REF" \
          --arg eventName "$GITHUB_EVENT_NAME" \
          --arg repoId "$GITHUB_REPOSITORY_ID" \
          --arg repoOwnerId "$GITHUB_REPOSITORY_OWNER_ID" \
          --arg runnerEnv "$RUNNER_ENVIRONMENT" \
          --arg gitCommit "$GITHUB_SHA" \
          --arg builderId "https://github.com/$GITHUB_REPOSITORY/.github/workflows/build.yml@$GITHUB_REF" \
          --arg invocationId "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/attempts/1" \
          --arg workflowPath "${{ github.workflow }}" \
          '{
              "buildDefinition": {
                "buildType": "https://actions.github.io/buildtypes/workflow/v1",
                "externalParameters": {
                  "workflow": {
                    "ref": $ref,
                    "repository": "https://github.com/\($repo)",
                    "path": $workflowPath
                  }                 
                },
                "internalParameters": {
                  "github": {
                    "event_name": $eventName,
                    "repository_id": $repoId,
                    "repository_owner_id": $repoOwnerId,
                    "runner_environment": $runnerEnv
                  }
                },
                "resolvedDependencies": [
                  {
                    "uri": "git+https://github.com/\($repo)@\($ref)",
                    "digest": {
                      "gitCommit": $gitCommit
                    }
                  }
                ]
              },
              "runDetails": {
                "builder": {
                  "id": $builderId
                },
                "metadata": {
                  "invocationId": $invocationId,
                  "startedOn": $buildTimestamp,
                  "finishedOn": $buildTimestamp
                }
              }
          }' > "$OUTPUT_PATH"

        # Output the path for subsequent steps
        echo "provenance-path=$OUTPUT_PATH" >> "$GITHUB_OUTPUT"

branding:
  icon: 'shield'
  color: 'green'