name: 'Build Provenance'
description: 'Generate and display build provenance'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set GITHUB_TOKEN environment variable
      if: ${{ inputs.github-token == '' }}
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      shell: bash
    - name: Run compiled index.js
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
    - name: Display provenance.json
      run: cat provenance.json
      shell: bash